### ISSUE TITLE
Erreur d'execution

### ISSUE THREAD

**Issue by SachaLhopital** [MDHayden/CasseBrique#1]
Bug pendant la partie : la balle ne rebondis que vers la gauche, quelque soit l'angle. 

W8 - Visual Studio

**Comment by Koialle** [comment]
Oulah, je ne sais pas comment on gère les issues encore.
Oui j'ai vu, c'est juste que quelqu'un s'est amusé à faire des tests sur le rebond et n'a pas décommenté la bonne portion de code avant de commit le projet x).
Du coup problème résolu en locale mais pas encore commit + améliorations à venir.

Je suppose qu'il faut que je close l'issue seulement après avoir référencer le commit ?

**Comment by Koialle** [comment]
J'ai oublié de préciser dans le commit que la correction a été faite. En tout cas elle est faite.
cddee36df9508147d782d59bbcfcef4593a8eb3f

**Comment by SachaLhopital** [comment]
Si le problème est résolu en ligne : tu peux close issue :) 

Merci

**Comment by Koialle** [comment]
:+1: :)
